import "server-only";
import { getIntegrationSecrets } from "@/lib/integration-secrets";

// youtube-transcript.io takes up to 50 video ids per POST and is rate limited
// to 5 requests / 10s account-wide, so every YouTube source in a script goes
// out in one call.
//
// The published docs do not describe the response body, so the parser below
// probes for timed cues and falls back to plain text. Timed cues matter: they
// are what will later let a locked fact deep-link to a moment in the video.

const ENDPOINT = "https://www.youtube-transcript.io/api/transcripts";
const BATCH_LIMIT = 50;

export type TranscriptResult = {
  videoId: string;
  ok: boolean;
  error?: string;
  title?: string;
  author?: string;
  durationSec?: number;
  captionKind: "manual" | "auto" | "unknown";
  rawText: string;
  segments?: { text: string; startSec: number }[];
};

type Unknown = Record<string, unknown>;

function asEntries(payload: unknown): Unknown[] {
  const root = payload as Unknown | null;
  const candidate = root?.transcripts ?? root?.data ?? payload;
  if (Array.isArray(candidate)) return candidate as Unknown[];
  if (candidate && typeof candidate === "object") return [candidate as Unknown];
  return [];
}

/** First array of cue-like objects anywhere in the entry. */
function findCues(node: unknown, depth = 0): Unknown[] | null {
  if (depth > 6 || !node || typeof node !== "object") return null;
  if (Array.isArray(node)) {
    const looksLikeCues = node.some(
      (c) =>
        c &&
        typeof c === "object" &&
        ("text" in c || "snippet" in c) &&
        ("start" in c || "offset" in c || "startMs" in c || "start_ms" in c || "dur" in c),
    );
    if (looksLikeCues) return node as Unknown[];
    for (const child of node) {
      const found = findCues(child, depth + 1);
      if (found) return found;
    }
    return null;
  }
  for (const value of Object.values(node as Unknown)) {
    const found = findCues(value, depth + 1);
    if (found) return found;
  }
  return null;
}

function cueSeconds(cue: Unknown): number {
  const raw = cue.start ?? cue.offset ?? cue.startMs ?? cue.start_ms ?? cue.startTime ?? 0;
  const n = typeof raw === "string" ? Number(raw) : Number(raw ?? 0);
  if (!Number.isFinite(n)) return 0;
  // Anything past ~28 hours is milliseconds, not seconds.
  return n > 100_000 ? n / 1000 : n;
}

function findString(node: unknown, keys: string[], minLength: number, depth = 0): string | null {
  if (depth > 5 || !node || typeof node !== "object") return null;
  const obj = node as Unknown;
  for (const key of keys) {
    const v = obj[key];
    if (typeof v === "string" && v.trim().length >= minLength) return v;
  }
  for (const value of Object.values(obj)) {
    const found = findString(value, keys, minLength, depth + 1);
    if (found) return found;
  }
  return null;
}

function detectCaptionKind(entry: Unknown): TranscriptResult["captionKind"] {
  const blob = JSON.stringify(entry).toLowerCase();
  if (/"(?:isgenerated|auto_generated|isautogenerated)"\s*:\s*true/.test(blob)) return "auto";
  if (/"(?:isgenerated|auto_generated|isautogenerated)"\s*:\s*false/.test(blob)) return "manual";
  if (/asr|auto-generated|autogenerated/.test(blob)) return "auto";
  return "unknown";
}

function matchEntry(entries: Unknown[], videoId: string): Unknown | undefined {
  const byId = entries.find((e) => {
    const id = e.id ?? e.videoId ?? e.video_id;
    return typeof id === "string" && id === videoId;
  });
  if (byId) return byId;
  return entries.length === 1 ? entries[0] : undefined;
}

async function postTranscripts(token: string, ids: string[]): Promise<unknown> {
  const res = await fetch(ENDPOINT, {
    method: "POST",
    headers: { Authorization: `Basic ${token}`, "Content-Type": "application/json" },
    body: JSON.stringify({ ids }),
    signal: AbortSignal.timeout(60_000),
  });

  if (res.status === 429) {
    const wait = Number(res.headers.get("retry-after") ?? 10);
    await new Promise((r) => setTimeout(r, Math.min(wait, 30) * 1000));
    return postTranscripts(token, ids);
  }
  if (res.status === 401 || res.status === 403) {
    throw new Error("Transcript API rejected the token — check it in Settings → Integrations");
  }
  if (!res.ok) {
    throw new Error(`Transcript API returned ${res.status}`);
  }
  return res.json();
}

/**
 * Fetch transcripts for a batch of video ids. Throws only on problems that
 * affect the whole call (missing token, auth); per-video failures come back as
 * entries with ok: false.
 */
export async function fetchTranscripts(
  workspaceId: string,
  videoIds: string[],
): Promise<TranscriptResult[]> {
  if (!videoIds.length) return [];

  const secrets = await getIntegrationSecrets(workspaceId, "youtube_transcript");
  const token = secrets?.apiToken;
  if (!token) {
    throw new Error(
      "No YouTube Transcript API token. Add one in Settings → Integrations.",
    );
  }

  const results: TranscriptResult[] = [];

  for (let i = 0; i < videoIds.length; i += BATCH_LIMIT) {
    const batch = videoIds.slice(i, i + BATCH_LIMIT);
    const payload = await postTranscripts(token, batch);
    const entries = asEntries(payload);

    for (const videoId of batch) {
      const entry = matchEntry(entries, videoId);
      if (!entry) {
        results.push({
          videoId,
          ok: false,
          captionKind: "unknown",
          rawText: "",
          error: "No captions available — paste the transcript manually instead",
        });
        continue;
      }

      const cues = findCues(entry);
      const segments = cues
        ?.map((c) => ({
          text: String(c.text ?? c.snippet ?? "").trim(),
          startSec: cueSeconds(c),
        }))
        .filter((s) => s.text);

      const rawText =
        segments?.map((s) => s.text).join(" ").trim() ||
        findString(entry, ["transcript", "text", "content", "plainText"], 200) ||
        "";

      results.push({
        videoId,
        ok: rawText.length > 0,
        error: rawText ? undefined : "Transcript came back empty",
        title: findString(entry, ["title"], 1) ?? undefined,
        author: findString(entry, ["author", "channel", "channelName"], 1) ?? undefined,
        captionKind: detectCaptionKind(entry),
        rawText,
        segments: segments?.length ? segments : undefined,
      });
    }
  }

  return results;
}

/** Human-subtitled sources are more trustworthy than auto-captioned ones. */
export function trustFromCaptionKind(kind: TranscriptResult["captionKind"]): number {
  if (kind === "manual") return 3;
  if (kind === "auto") return 1;
  return 2;
}
