// Stage 01 — fetch transcripts.
//
// youtube-transcript.io takes up to 50 video ids per POST and is rate limited
// to 5 requests / 10s account-wide, so every YouTube source in the script goes
// out in ONE call.
//
// This stage answers a question the published docs do not: whether the
// response carries per-segment timestamps. That decides whether a locked fact
// can deep-link to a moment in the video, so the raw body is written to disk
// verbatim for inspection and the verdict is printed.
import { SOURCES, type SpikeSource } from "../config";
import { writeStage, heading } from "../lib/io";

export type FetchedSource = {
  id: string;
  type: SpikeSource["type"];
  url?: string;
  title?: string;
  trustLevel: number;
  videoId?: string;
  rawText: string;
  /** Present only when the API returns timed cues. */
  segments?: { text: string; startSec: number }[];
  captionKind: "manual" | "auto" | "unknown" | "n/a";
  ok: boolean;
  error?: string;
};

const ENDPOINT = "https://www.youtube-transcript.io/api/transcripts";

export function parseVideoId(url: string): string | null {
  try {
    const u = new URL(url.trim());
    const host = u.hostname.replace(/^www\./, "");
    if (host === "youtu.be") return u.pathname.slice(1).split("/")[0] || null;
    if (!host.endsWith("youtube.com")) return null;
    const v = u.searchParams.get("v");
    if (v) return v;
    const m = u.pathname.match(/^\/(?:shorts|embed|live|v)\/([^/?]+)/);
    return m ? m[1] : null;
  } catch {
    return null;
  }
}

type Unknown = Record<string, unknown>;

function asArray(value: unknown): Unknown[] {
  if (Array.isArray(value)) return value as Unknown[];
  if (value && typeof value === "object") return [value as Unknown];
  return [];
}

/** First array of cue-like objects found anywhere in the entry. */
function findCues(node: unknown, depth = 0): Unknown[] | null {
  if (depth > 6 || !node || typeof node !== "object") return null;
  if (Array.isArray(node)) {
    const looksLikeCues = node.some(
      (c) =>
        c &&
        typeof c === "object" &&
        ("text" in c || "snippet" in c) &&
        ("start" in c || "offset" in c || "startMs" in c || "start_ms" in c || "dur" in c),
    );
    if (looksLikeCues) return node as Unknown[];
    for (const child of node) {
      const found = findCues(child, depth + 1);
      if (found) return found;
    }
    return null;
  }
  for (const value of Object.values(node as Unknown)) {
    const found = findCues(value, depth + 1);
    if (found) return found;
  }
  return null;
}

function cueSeconds(cue: Unknown): number {
  const raw =
    cue.start ?? cue.offset ?? cue.startMs ?? cue.start_ms ?? cue.startTime ?? 0;
  const n = typeof raw === "string" ? Number(raw) : Number(raw ?? 0);
  if (!Number.isFinite(n)) return 0;
  // Heuristic: anything past ~28 hours is milliseconds, not seconds.
  return n > 100_000 ? n / 1000 : n;
}

function findPlainText(node: unknown, depth = 0): string | null {
  if (depth > 6 || !node || typeof node !== "object") return null;
  const obj = node as Unknown;
  for (const key of ["transcript", "text", "content", "plainText"]) {
    const v = obj[key];
    if (typeof v === "string" && v.trim().length > 200) return v;
  }
  for (const value of Object.values(obj)) {
    const found = findPlainText(value, depth + 1);
    if (found) return found;
  }
  return null;
}

function findTitle(node: unknown, depth = 0): string | undefined {
  if (depth > 4 || !node || typeof node !== "object") return undefined;
  const obj = node as Unknown;
  if (typeof obj.title === "string" && obj.title.trim()) return obj.title;
  for (const value of Object.values(obj)) {
    const found = findTitle(value, depth + 1);
    if (found) return found;
  }
  return undefined;
}

function detectCaptionKind(entry: Unknown): FetchedSource["captionKind"] {
  const blob = JSON.stringify(entry).toLowerCase();
  if (/"(?:isgenerated|auto_generated|isautogenerated)"\s*:\s*true/.test(blob)) return "auto";
  if (/"(?:isgenerated|auto_generated|isautogenerated)"\s*:\s*false/.test(blob)) return "manual";
  if (/asr|auto-generated|autogenerated/.test(blob)) return "auto";
  return "unknown";
}

function matchEntry(entries: Unknown[], videoId: string): Unknown | undefined {
  return (
    entries.find((e) => {
      const id = e.id ?? e.videoId ?? e.video_id;
      return typeof id === "string" && id === videoId;
    }) ?? (entries.length === 1 ? entries[0] : undefined)
  );
}

async function fetchTranscripts(ids: string[]): Promise<{ raw: unknown; entries: Unknown[] }> {
  const token = process.env.YOUTUBE_TRANSCRIPT_TOKEN;
  if (!token) throw new Error("YOUTUBE_TRANSCRIPT_TOKEN is not set — add it to .env");

  const res = await fetch(ENDPOINT, {
    method: "POST",
    headers: {
      Authorization: `Basic ${token}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ ids }),
  });

  if (res.status === 429) {
    const wait = Number(res.headers.get("retry-after") ?? 10);
    console.log(`  rate limited, waiting ${wait}s`);
    await new Promise((r) => setTimeout(r, wait * 1000));
    return fetchTranscripts(ids);
  }
  if (!res.ok) {
    throw new Error(`transcript api ${res.status}: ${(await res.text()).slice(0, 400)}`);
  }

  const raw = await res.json();
  const entries = asArray(
    (raw as Unknown)?.transcripts ?? (raw as Unknown)?.data ?? raw,
  );
  return { raw, entries };
}

export async function run(): Promise<FetchedSource[]> {
  heading("Stage 01 — fetch");

  const youtube = SOURCES.filter((s) => s.type === "youtube");
  const ids = youtube
    .map((s) => ({ source: s, videoId: s.url ? parseVideoId(s.url) : null }))
    .filter((x): x is { source: SpikeSource; videoId: string } => !!x.videoId);

  for (const s of youtube) {
    if (!s.url || !parseVideoId(s.url)) {
      console.log(`  ${s.id}: could not parse a video id from ${s.url ?? "(no url)"}`);
    }
  }

  let entries: Unknown[] = [];
  if (ids.length) {
    console.log(`  requesting ${ids.length} transcript(s) in one call`);
    const { raw, entries: got } = await fetchTranscripts(ids.map((x) => x.videoId));
    writeStage("01-fetch.raw", raw);
    entries = got;
    console.log("  raw response written to output/01-fetch.raw.json");
  }

  const results: FetchedSource[] = [];

  for (const source of SOURCES) {
    const base = {
      id: source.id,
      type: source.type,
      url: source.url,
      title: source.title,
      trustLevel: source.trustLevel ?? 2,
    };

    if (source.type === "text") {
      const text = (source.text ?? "").trim();
      results.push({
        ...base,
        rawText: text,
        captionKind: "n/a",
        ok: text.length > 0,
        error: text ? undefined : "empty text source",
      });
      continue;
    }

    const videoId = source.url ? parseVideoId(source.url) : null;
    if (!videoId) {
      results.push({
        ...base,
        rawText: "",
        captionKind: "n/a",
        ok: false,
        error: "unparseable youtube url",
      });
      continue;
    }

    const entry = matchEntry(entries, videoId);
    if (!entry) {
      results.push({
        ...base,
        videoId,
        rawText: source.text?.trim() ?? "",
        captionKind: "n/a",
        ok: !!source.text?.trim(),
        error: "no transcript returned — needs the ASR fallback or a manual paste",
      });
      continue;
    }

    const cues = findCues(entry);
    const segments = cues?.map((c) => ({
      text: String(c.text ?? c.snippet ?? "").trim(),
      startSec: cueSeconds(c),
    }));
    const rawText =
      segments?.map((s) => s.text).join(" ").trim() || findPlainText(entry) || "";

    results.push({
      ...base,
      videoId,
      title: base.title ?? findTitle(entry),
      rawText,
      segments,
      captionKind: detectCaptionKind(entry),
      ok: rawText.length > 0,
      error: rawText ? undefined : "entry returned but no text found — inspect the raw dump",
    });
  }

  const timed = results.filter((r) => r.segments?.length);
  heading("Provenance verdict");
  if (timed.length) {
    console.log(`  TIMESTAMPS: yes — ${timed.length}/${results.length} sources carry timed cues.`);
    console.log("  Facts can deep-link to a moment in the video. Keep the segments.");
  } else if (results.some((r) => r.type === "youtube" && r.ok)) {
    console.log("  TIMESTAMPS: no — the API returned text without timed cues.");
    console.log("  Provenance degrades to character offsets. Check 01-fetch.raw.json");
    console.log("  for a timed variant before accepting this.");
  }

  for (const r of results) {
    const words = r.rawText.split(/\s+/).filter(Boolean).length;
    console.log(
      `  ${r.id}  ${r.ok ? "ok" : "FAILED"}  ${words} words  captions=${r.captionKind}` +
        (r.error ? `  (${r.error})` : ""),
    );
  }

  writeStage("01-fetch", results);
  return results;
}
